#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi

if [ ! -d "venv" ]; then
  echo "==> Creating virtualenv…"
  virtualenv -p python3.8 venv
fi

if [ -d "venv" ]; then
  echo "==> Activating virtualenv…"
  # shellcheck source=../venv/bin/activate
  . ./venv/bin/activate
fi

if [ -f "requirements.txt" ]; then
  echo "==> Installing pip dependencies…"
  pip install -r requirements.txt
fi

if [ -f "setup.py" ]; then
  echo "==> Installing module…"
  pip install -e .
fi
