#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

# # shellcheck source=../venv/bin/activate
# . venv/bin/activate

# boot the app and any other necessary processes.
overmind start
