name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag chrisbot:${IMAGE_TAG}
        docker tag chrisbot:${IMAGE_TAG} docker.pkg.github.com/tebriel/chrisbot/chrisbot:${IMAGE_TAG}
        docker login https://docker.pkg.github.com -u tebriel --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/tebriel/chrisbot/chrisbot:${IMAGE_TAG}
